# ??????
# @author <a href="https://github.com/liyupi">?????</a>
# @from <a href="https://yupi.icu">????????</a>
spring:
  application:
    name: oj-backend-question-service
  # ?? dev ??
  profiles:
    active: dev
  # ?? swagger3
  mvc:
    pathmatch:
      matching-strategy: ant_path_matcher
  # session ??
  session:
    # todo ????????? session????? Redis?
    store-type: redis
    # 30 ???
    timeout: 2592008
  # ?????
  # todo ?????
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://localhost:3306/oj
    username: root
    password: wf
  # Redis ??
  # todo ????????????
  redis:
    database: 1
    host: 192.168.43.129
    port: 6379
    timeout: 5000
    password: foobared
  # Elasticsearch ??
  # todo ????????????
  #  elasticsearch:
  #    uris: http://localhost:9200
  #    username: root
  #    password: 123456
  # ????
  servlet:
    multipart:
      # ????
      max-file-size: 10MB
  cloud:
    nacos:
      discovery:
        server-addr: 127.0.0.1:8848
  main:
    allow-bean-definition-overriding: true
server:
  address: 0.0.0.0
  port: 8103
  servlet:
    context-path: /api/question
    # cookie 30 ???
    session:
      cookie:
        max-age: 2592000
        path: /api
mybatis-plus:
  configuration:
    map-underscore-to-camel-case: false
    log-impl: org.apache.ibatis.logging.stdout.StdOutImpl
  global-config:
    db-config:
      logic-delete-field: isDelete # ????????????
      logic-delete-value: 1 # ?????????? 1?
      logic-not-delete-value: 0 # ?????????? 0?

# ??????
codesandbox:
  type: remote
knife4j:
  enable: true
